#!/bin/bash

# Function calls to generate sqlite3 database
function sql_languages() { echo -e "\e[1A\e[KAdding Languages ($2/$3)" ; sqlite3 $HOME/.dnd.db "insert or ignore into languages (name) values ('$1');" ; }
function sql_equipment() { echo -e "\e[1A\e[KAdding Equipment ($4/$5)" ; sqlite3 $HOME/.dnd.db "insert or ignore into equipment (name, price, weight) values ('$1', '$2', '$3');" ; }
function sql_spells() { echo -e "\e[1A\e[KAdding Spells ($7/$8)" ; sqlite3 $HOME/.dnd.db "insert or ignore into spells (class, name, level, cast_time, range, duration) values ('$1', '$2', '$3', '$4', '$5', '$6');" ; }

# Check if sqlite3 is installed
if ! [ -x "$(command -v sqlite3)" ]
then
	echo "Error: sqlite3 is not installed." >&2
	exit 1
else
	echo "Found sqlite3." >&2
fi

echo "Adding Languages"
sqlite3 $HOME/.dnd.db "create table if not exists languages (name TEXT, UNIQUE(name));"
sql_languages 'Common' 1 17
sql_languages 'Dwarvish' 2 17
sql_languages 'Elvish' 3 17
sql_languages 'Giant' 4 17
sql_languages 'Gnomish' 5 17
sql_languages 'Goblin' 6 17
sql_languages 'Halfling' 7 17
sql_languages 'Orc' 8 17
sql_languages 'Abyssal' 9 17
sql_languages 'Celestial' 10 17
sql_languages 'Draconic' 11 17
sql_languages 'Deep\ Speech' 12 17
sql_languages 'Infernal' 13 17
sql_languages 'Primordial' 14 17
sql_languages 'Sylvan' 15 17
sql_languages 'Undercommon' 16 17
sql_languages 'Druidic' 17 17

echo "Adding Equipment"
sqlite3 $HOME/.dnd.db "create table if not exists equipment (name TEXT, price TEXT, weight TEXT, UNIQUE(name, price, weight));"
sql_equipment 'Abacus' 2 2 1 135
sql_equipment 'Acid (vial)' 25 1 2 135
sql_equipment 'Alchemists fire (flask)' 50 1 3 135
sql_equipment 'Alchemists supplies' 50 8 4 135
sql_equipment 'Antitoxin (vial)' 50 0 5 135
sql_equipment 'Arrows (20)' 1 1 6 135
sql_equipment 'Backpack' 2 5 7 135
sql_equipment 'Bagpipes' 30 6 8 135
sql_equipment 'Ball bearings (bag of 1000)' 1 2 9 135
sql_equipment 'Barrel' 2 70 10 135
sql_equipment 'Basket' 0.4 2 11 135
sql_equipment 'Bedroll' 1 7 12 135
sql_equipment 'Bell' 1 0 13 135
sql_equipment 'Blanket' 0.5 3 14 135
sql_equipment 'Block and tackle' 1 5 15 135
sql_equipment 'Blowgun needles (50)' 1 1 16 135
sql_equipment 'Book' 25 5 17 135
sql_equipment 'Glass Bottle' 2 2 18 135
sql_equipment 'Brewers Supplies' 20 9 19 135
sql_equipment 'Bucket' 0.05 2 20 135
sql_equipment 'Calligraphers Supplies' 10 5 21 135
sql_equipment 'Caltrops (bag of 20)' 1 2 22 135
sql_equipment 'Candle' 0.01 0 23 135
sql_equipment 'Carpenters Tools' 8 6 24 135
sql_equipment 'Cartographers Tools' 15 6 25 135
sql_equipment 'Case crossbow bolt' 1 1 26 135
sql_equipment 'Case map or scroll' 1 1 27 135
sql_equipment 'Chain (10 feet)' 5 10 28 135
sql_equipment 'Chalk (1 piece)' 0.01 0 29 135
sql_equipment 'Chest' 5 25 30 135
sql_equipment 'Climbers kit' 25 12 31 135
sql_equipment 'Clothes Common' 0.5 3 32 135
sql_equipment 'Clothes Costume' 5 4 33 135
sql_equipment 'Clothes Fine' 15 6 34 135
sql_equipment 'Clothes Travelers' 2 4 35 135
sql_equipment 'Cobblers Tools' 5 5 36 135
sql_equipment 'Component pouch' 25 2 37 135
sql_equipment 'Cooks Utensils' 1 8 38 135
sql_equipment 'Crossbow bolts (20)' 1 1.5 39 135
sql_equipment 'Crowbar' 2 5 40 135
sql_equipment 'Crystal' 10 1 41 135
sql_equipment 'Dice Set' 0.1 0 42 135
sql_equipment 'Disguise Kit' 25 3 43 135
sql_equipment 'Dragonchess Set' 1 0.5 44 135
sql_equipment 'Drum' 6 3 45 135
sql_equipment 'Dulcimer' 25 10 46 135
sql_equipment 'Fishing tackle' 1 4 47 135
sql_equipment 'Flask or tankard' 0.02 1 48 135
sql_equipment 'Flute' 2 1 49 135
sql_equipment 'Forgery Kit' 15 5 50 135
sql_equipment 'Glassblowers Tools' 30 5 51 135
sql_equipment 'Grappling hook' 2 4 52 135
sql_equipment 'Hammer sledge' 2 10 53 135
sql_equipment 'Hammer' 1 3 54 135
sql_equipment 'Healers kit' 5 3 55 135
sql_equipment 'Herbalism Kit' 5 3 56 135
sql_equipment 'Holy Symbol (Amulet)' 5 1 57 135
sql_equipment 'Holy Symbol (Emblem)' 5 0 58 135
sql_equipment 'Holy Symbol (Reliquary)' 5 2 59 135
sql_equipment 'Holy water (flask)' 25 1 60 135
sql_equipment 'Horn' 3 2 61 135
sql_equipment 'Hourglass' 25 1 62 135
sql_equipment 'Hunting trap' 5 25 63 135
sql_equipment 'Ink (1 ounce bottle)' 10 0 64 135
sql_equipment 'Ink pen' 0.02 0 65 135
sql_equipment 'Jewelers Tools' 25 2 66 135
sql_equipment 'Jug or pitcher' 0.02 4 67 135
sql_equipment 'Ladder (10-foot)' 0.1 25 68 135
sql_equipment 'Lamp' 0.5 1 69 135
sql_equipment 'Lantern bullseye' 10 2 70 135
sql_equipment 'Lantern hooded' 5 2 71 135
sql_equipment 'Leatherworkers Tools' 5 5 72 135
sql_equipment 'Lock' 10 1 73 135
sql_equipment 'Lute' 35 2 74 135
sql_equipment 'Lyre' 30 2 75 135
sql_equipment 'Magnifying glass' 100 0 76 135
sql_equipment 'Manacles' 2 6 77 135
sql_equipment 'Masons Tools' 10 8 78 135
sql_equipment 'Mess kit' 0.2 1 79 135
sql_equipment 'Mirror steel' 5 0.5 80 135
sql_equipment 'Navigators Tools' 25 2 81 135
sql_equipment 'Oil (flask)' 0.1 1 82 135
sql_equipment 'Orb' 20 3 83 135
sql_equipment 'Painters Supplies' 10 5 84 135
sql_equipment 'Pan flute' 12 2 85 135
sql_equipment 'Paper (one sheet)' 0.2 0 86 135
sql_equipment 'Parchment (one sheet)' 0.1 0 87 135
sql_equipment 'Perfume (vial)' 5 0 88 135
sql_equipment 'Pick miners' 2 10 89 135
sql_equipment 'Piton' 0.05 0.25 90 135
sql_equipment 'Playing Card Set' 5 0 91 135
sql_equipment 'Poison basic (vial)' 100 0 92 135
sql_equipment 'Poisoners Kit' 50 2 93 135
sql_equipment 'Pole (10-foot)' 0.05 7 94 135
sql_equipment 'Potion of healing' 50 0.5 95 135
sql_equipment 'Pot iron' 2 10 96 135
sql_equipment 'Potters Tools' 10 3 97 135
sql_equipment 'Pouch' 0.5 1 98 135
sql_equipment 'Quiver' 1 1 99 135
sql_equipment 'Ram portable' 4 35 100 135
sql_equipment 'Rations (1 day)' 0.5 2 101 135
sql_equipment 'Robes' 1 4 102 135
sql_equipment 'Rod' 10 2 103 135
sql_equipment 'Rope hempen (50 feet)' 1 10 104 135
sql_equipment 'Rope silk (50 feet)' 10 5 105 135
sql_equipment 'Sack' 0.01 0.5 106 135
sql_equipment 'Scale merchants' 5 3 107 135
sql_equipment 'Sealing wax' 0.5 0 108 135
sql_equipment 'Shawm' 2 1 109 135
sql_equipment 'Shovel' 2 5 110 135
sql_equipment 'Signal whistle' 0.05 0 111 135
sql_equipment 'Signet ring' 5 0 112 135
sql_equipment 'Sling bullets (20)' 0.04 1.5 113 135
sql_equipment 'Smiths Tools' 20 8 114 135
sql_equipment 'Spellbook' 50 3 115 135
sql_equipment 'Spikes iron (10)' 1 5 116 135
sql_equipment 'Sprig of mistletoe' 1 0 117 135
sql_equipment 'Spyglass' 1000 1 118 135
sql_equipment 'Staff' 5 4 119 135
sql_equipment 'Tent two-person' 2 20 120 135
sql_equipment 'Thieves Tools' 25 1 121 135
sql_equipment 'Three-Dragon Ante Set' 1 0 122 135
sql_equipment 'Tinderbox' 0.5 1 123 135
sql_equipment 'Tinkers Tools' 50 10 124 135
sql_equipment 'Torch' 0.01 1 125 135
sql_equipment 'Totem' 1 0 126 135
sql_equipment 'Vial' 1 0 127 135
sql_equipment 'Viol' 30 1 128 135
sql_equipment 'Wand' 10 1 129 135
sql_equipment 'Waterskin' 0.2 5 130 135
sql_equipment 'Weavers tools' 1 5 131 135
sql_equipment 'Whetstone' 0.01 1 132 135
sql_equipment 'Woodcarvers Tools' 1 5 133 135
sql_equipment 'Wooden staff' 5 4 134 135
sql_equipment 'Yew Wand' 10 1 135 135

echo "Adding spells"
sqlite3 $HOME/.dnd.db "create table if not exists spells (class TEXT, name TEXT, level TEXT, cast_time TEXT, range TEXT, duration TEXT, UNIQUE(class, name, level, cast_time, range, duration));"
sql_spells "Bard" 'Blade Ward' 0 '1 action' 'self' '1 round'
sql_spells 'Bard' 'Dancing Lights' 0 '1 action' '120 feet' 'concentration, up to 1 minute'
sql_spells 'Bard' 'Friends' 0 '1 action' 'self' 'concentration, up to 1 minute'
sql_spells 'Bard' 'Light' 0 '1 action' 'touch' '1 hour'
sql_spells 'Bard' 'Mage Hand' 0 '1 action' '30 feet' '1 minute'
sql_spells 'Bard' 'Mending' 0 '1 minute' 'touch' 'instantaneous'
sql_spells 'Bard' 'Message' 0 '1 action' '120 feet' '1 round'
sql_spells 'Bard' 'Minor Illusion' 0 '1 action' '30 feet' '1 minute'
sql_spells 'Bard' 'Prestidgitation' 0 '1 action' '10 feet' 'Up to 1 hour'
sql_spells 'Bard' 'True Strike' 0 '1 action' '30 feet' 'concentration, up to 1 round'
sql_spells 'Bard' 'Vicious Mockery' 0 '1 action' '60 feet' 'Instantaneous'
sql_spells 'Bard' 'Animal Friendship' 1 '' '' ''
sql_spells 'Bard' 'Bane' 1 '' '' ''
sql_spells 'Bard' 'Charm Person' 1 '' '' ''
sql_spells 'Bard' 'Comprehended Languages' 1 '' '' ''
sql_spells 'Bard' 'Cure Wounds' 1 '' '' ''
sql_spells 'Bard' 'Detect Magic' 1 '' '' ''
sql_spells 'Bard' 'Disguise Self' 1 '' '' ''
sql_spells 'Bard' 'Dissonant Whispers' 1 '' '' ''
sql_spells 'Bard' 'Faerie Fire' 1 '' '' ''
sql_spells 'Bard' 'Feather Fall' 1 '' '' ''
sql_spells 'Bard' 'Healing Wound' 1 '' '' ''
sql_spells 'Bard' 'Heroism' 1 '' '' ''
sql_spells 'Bard' 'Identify' 1 '' '' ''
sql_spells 'Bard' 'Illusory Script' 1 '' '' ''
sql_spells 'Bard' 'Longstrider' 1 '' '' ''
sql_spells 'Bard' 'Silent Image' 1 '' '' ''
sql_spells 'Bard' 'Sleep' 1 '' '' ''
sql_spells 'Bard' 'Speak with Animals' 1 '' '' ''
sql_spells 'Bard' 'Tashas Hideous Laughter' 1 '' '' ''
sql_spells 'Bard' 'Thunderwave' 1 '' '' ''
sql_spells 'Bard' 'Unseen Servent' 1 '' '' ''
sql_spells 'Bard' 'Animal Messanger' 2 '' '' ''
sql_spells 'Bard' 'Blindness/Deafness' 2 '' '' ''
sql_spells 'Bard' 'Calm Emotions' 2 '' '' ''
sql_spells 'Bard' 'Cloud of Daggers' 2 '' '' ''
sql_spells 'Bard' 'Crown of Madness' 2 '' '' ''
sql_spells 'Bard' 'Detect Thoughts' 2 '' '' ''
sql_spells 'Bard' 'Enahnce Ability' 2 '' '' ''
sql_spells 'Bard' 'Enthrall' 2 '' '' ''
sql_spells 'Bard' 'Heat Metal' 2 '' '' ''
sql_spells 'Bard' 'Hold Person' 2 '' '' ''
sql_spells 'Bard' 'Invisibility' 2 '' '' ''
sql_spells 'Bard' 'Knock' 2 '' '' ''
sql_spells 'Bard' 'Lesser Restoration' 2 '' '' ''
sql_spells 'Bard' 'Locate Animals or Plants' 2 '' '' ''
sql_spells 'Bard' 'Locate Object' 2 '' '' ''
sql_spells 'Bard' 'Magic Mouth' 2 '' '' ''
sql_spells 'Bard' 'Phantasmal Force' 2 '' '' ''
sql_spells 'Bard' 'See Invisibility' 2 '' '' ''
sql_spells 'Bard' 'Shatter' 2 '' '' ''
sql_spells 'Bard' 'Silence' 2 '' '' ''
sql_spells 'Bard' 'Suggestion' 2 '' '' ''
sql_spells 'Bard' 'Zone of Truth' 2 '' '' ''
sql_spells 'Bard' 'Bestow Curse' 3 '' '' ''
sql_spells 'Bard' 'Clairvoyance' 3 '' '' ''
sql_spells 'Bard' 'Dispel Magic' 3 '' '' ''
sql_spells 'Bard' 'Fear' 3 '' '' ''
sql_spells 'Bard' 'Feign Death' 3 '' '' ''
sql_spells 'Bard' 'Glyph of Warding' 3 '' '' ''
sql_spells 'Bard' 'Hypnotic Pattern' 3 '' '' ''
sql_spells 'Bard' 'Leomunds Tiny Hut' 3 '' '' ''
sql_spells 'Bard' 'Major Image' 3 '' '' ''
sql_spells 'Bard' 'Nondetection' 3 '' '' ''
sql_spells 'Bard' 'Plant Growth' 3 '' '' ''
sql_spells 'Bard' 'Sending' 3 '' '' ''
sql_spells 'Bard' 'Speak with Dead' 3 '' '' ''
sql_spells 'Bard' 'Speak with Plants' 3 '' '' ''
sql_spells 'Bard' 'Stinking Cloud' 3 '' '' ''
sql_spells 'Bard' 'Tongues' 3 '' '' ''
sql_spells 'Bard' 'Compulsion' 4 '' '' ''
sql_spells 'Bard' 'Confusion' 4 '' '' ''
sql_spells 'Bard' 'Dimension Door' 4 '' '' ''
sql_spells 'Bard' 'Freedom of Movement' 4 '' '' ''
sql_spells 'Bard' 'Greater Invisibility' 4 '' '' ''
sql_spells 'Bard' 'Hallucinatory Terrain' 4 '' '' ''
sql_spells 'Bard' 'Locate Creature' 4 '' '' ''
sql_spells 'Bard' 'Polymorph' 4 '' '' ''
sql_spells 'Bard' 'Animate Objects' 5 '' '' ''
sql_spells 'Bard' 'Awaken' 5 '' '' ''
sql_spells 'Bard' 'Dominate Person' 5 '' '' ''
sql_spells 'Bard' 'Dream' 5 '' '' ''
sql_spells 'Bard' 'Geas' 5 '' '' ''
sql_spells 'Bard' 'Greater Restoration' 5 '' '' ''
sql_spells 'Bard' 'Hold Monster' 5 '' '' ''
sql_spells 'Bard' 'Legend Lore' 5 '' '' ''
sql_spells 'Bard' 'Mass Cure Wounds' 5 '' '' ''
sql_spells 'Bard' 'Mislead' 5 '' '' ''
sql_spells 'Bard' 'Modify Memory' 5 '' '' ''
sql_spells 'Bard' 'Planar Binding' 5 '' '' ''
sql_spells 'Bard' 'Raise Dead' 5 '' '' ''
sql_spells 'Bard' 'Scything' 5 '' '' ''
sql_spells 'Bard' 'Seeming' 5 '' '' ''
sql_spells 'Bard' 'Teleportation Circle' 5 '' '' ''
sql_spells 'Bard' 'Eyebite' 6 '' '' ''
sql_spells 'Bard' 'Find the Path' 6 '' '' ''
sql_spells 'Bard' 'Guards and Wards' 6 '' '' ''
sql_spells 'Bard' 'Mass Suggestion' 6 '' '' ''
sql_spells 'Bard' 'Ottos Irresistible Dance' 6 '' '' ''
sql_spells 'Bard' 'Programmed Illusion' 6 '' '' ''
sql_spells 'Bard' 'True Seeing' 6 '' '' ''
sql_spells 'Bard' 'Etheralness' 7 '' '' ''
sql_spells 'Bard' 'Forcecage' 7 '' '' ''
sql_spells 'Bard' 'Mirage Arcane' 7 '' '' ''
sql_spells 'Bard' 'Mordenkainens Magnificent Mansion' 7 '' '' ''
sql_spells 'Bard' 'Mordenkainens Sword' 7 '' '' ''
sql_spells 'Bard' 'Project Image' 7 '' '' ''
sql_spells 'Bard' 'Regenerate' 7 '' '' ''
sql_spells 'Bard' 'Resurrection' 7 '' '' ''
sql_spells 'Bard' 'Symbol' 7 '' '' ''
sql_spells 'Bard' 'Teleport' 7 '' '' ''
sql_spells 'Bard' 'Dominate Monster' 8 '' '' ''
sql_spells 'Bard' 'Feeblemind' 8 '' '' ''
sql_spells 'Bard' 'Glibness' 8 '' '' ''
sql_spells 'Bard' 'Mind Blank' 8 '' '' ''
sql_spells 'Bard' 'Power Word Stun' 8 '' '' ''
sql_spells 'Bard' 'Foresight' 9 '' '' ''
sql_spells 'Bard' 'Power Word Heal' 9 '' '' ''
sql_spells 'Bard' 'Power Word Kill' 9 '' '' ''
sql_spells 'Bard' 'True Polymorph' 9 '' '' ''
sql_spells 'Cleric' 'Guidance' 0 '' '' ''
sql_spells 'Cleric' 'Light' 0 '' '' ''
sql_spells 'Cleric' 'Mending' 0 '' '' ''
sql_spells 'Cleric' 'Resistance' 0 '' '' ''
sql_spells 'Cleric' 'Sacred Flame' 0 '' '' ''
sql_spells 'Cleric' 'Spare the Dying' 0 '' '' ''
sql_spells 'Cleric' 'Thaumaturgy' 0 '' '' ''
sql_spells 'Cleric' 'Blane' 1 '' '' ''
sql_spells 'Cleric' 'Bless' 1 '' '' ''
sql_spells 'Cleric' 'Command' 1 '' '' ''
sql_spells 'Cleric' 'Create or Destory Water' 1 '' '' ''
sql_spells 'Cleric' 'Cure Wounds' 1 '' '' ''
sql_spells 'Cleric' 'Detect Evil and Good' 1 '' '' ''
sql_spells 'Cleric' 'Detect Magic' 1 '' '' ''
sql_spells 'Cleric' 'Detect Poison and Disese' 1 '' '' ''
sql_spells 'Cleric' 'Guiding Bolt' 1 '' '' ''
sql_spells 'Cleric' 'Healing Wound' 1 '' '' ''
sql_spells 'Cleric' 'Inflict Wounds' 1 '' '' ''
sql_spells 'Cleric' 'Protection from Evil and Good' 1 '' '' ''
sql_spells 'Cleric' 'Purify Food and Drink' 1 '' '' ''
sql_spells 'Cleric' 'Sanctuary' 1 '' '' ''
sql_spells 'Cleric' 'Shield of Faith' 1 '' '' ''
sql_spells 'Cleric' 'Aid' 2 '' '' ''
sql_spells 'Cleric' 'Augury' 2 '' '' ''
sql_spells 'Cleric' 'Blindness/Deafness' 2 '' '' ''
sql_spells 'Cleric' 'Calm Emotions' 2 '' '' ''
sql_spells 'Cleric' 'Continual Flame' 2 '' '' ''
sql_spells 'Cleric' 'Enhance Ability' 2 '' '' ''
sql_spells 'Cleric' 'Find Traps' 2 '' '' ''
sql_spells 'Cleric' 'Gentle Response' 2 '' '' ''
sql_spells 'Cleric' 'Hold Person' 2 '' '' ''
sql_spells 'Cleric' 'Lesser Restoration' 2 '' '' ''
sql_spells 'Cleric' 'Locate Object' 2 '' '' ''
sql_spells 'Cleric' 'Prayer of Healing' 2 '' '' ''
sql_spells 'Cleric' 'Protection from Poison' 2 '' '' ''
sql_spells 'Cleric' 'Silence' 2 '' '' ''
sql_spells 'Cleric' 'Spiritual Weapon' 2 '' '' ''
sql_spells 'Cleric' 'Warding Bond' 2 '' '' ''
sql_spells 'Cleric' 'Zone of Truth' 2 '' '' ''
sql_spells 'Cleric' 'Animate Dead' 3 '' '' ''
sql_spells 'Cleric' 'Beacon of Hope' 3 '' '' ''
sql_spells 'Cleric' 'Bestow Curse' 3 '' '' ''
sql_spells 'Cleric' 'Clairvoyance' 3 '' '' ''
sql_spells 'Cleric' 'Create Food and Water' 3 '' '' ''
sql_spells 'Cleric' 'Daylight' 3 '' '' ''
sql_spells 'Cleric' 'Dispel Magic' 3 '' '' ''
sql_spells 'Cleric' 'Feign Death' 3 '' '' ''
sql_spells 'Cleric' 'Glyph of Warding' 3 '' '' ''
sql_spells 'Cleric' 'Magic Circle' 3 '' '' ''
sql_spells 'Cleric' 'Mass Healing Word' 3 '' '' ''
sql_spells 'Cleric' 'Meld into Stone' 3 '' '' ''
sql_spells 'Cleric' 'Protection from Energy' 3 '' '' ''
sql_spells 'Cleric' 'Remove Curse' 3 '' '' ''
sql_spells 'Cleric' 'Revivify' 3 '' '' ''
sql_spells 'Cleric' 'Sending' 3 '' '' ''
sql_spells 'Cleric' 'Speak with Dead' 3 '' '' ''
sql_spells 'Cleric' 'Spirit Guardians' 3 '' '' ''
sql_spells 'Cleric' 'Tounges' 3 '' '' ''
sql_spells 'Cleric' 'Water Walk' 3 '' '' ''
sql_spells 'Cleric' 'Banishment' 4 '' '' ''
sql_spells 'Cleric' 'Control Water' 4 '' '' ''
sql_spells 'Cleric' 'Death Ward' 4 '' '' ''
sql_spells 'Cleric' 'Divination' 4 '' '' ''
sql_spells 'Cleric' 'Freedom of Movement' 4 '' '' ''
sql_spells 'Cleric' 'Guardian of Faith' 4 '' '' ''
sql_spells 'Cleric' 'Locate Creature' 4 '' '' ''
sql_spells 'Cleric' 'Stone Shape' 4 '' '' ''
sql_spells 'Cleric' 'Commune' 5 '' '' ''
sql_spells 'Cleric' 'Contagion' 5 '' '' ''
sql_spells 'Cleric' 'Dispell Evil and Good' 5 '' '' ''
sql_spells 'Cleric' 'Flame Strike' 5 '' '' ''
sql_spells 'Cleric' 'Geas' 5 '' '' ''
sql_spells 'Cleric' 'Greater Restoration' 5 '' '' ''
sql_spells 'Cleric' 'Hallow' 5 '' '' ''
sql_spells 'Cleric' 'Inspect Plauge' 5 '' '' ''
sql_spells 'Cleric' 'Legond Lore' 5 '' '' ''
sql_spells 'Cleric' 'Mass Cure Wounds' 5 '' '' ''
sql_spells 'Cleric' 'Planar Binding' 5 '' '' ''
sql_spells 'Cleric' 'Raise Dead' 5 '' '' ''
sql_spells 'Cleric' 'Scrying' 5 '' '' ''
sql_spells 'Cleric' 'Blade Barrier' 6 '' '' ''
sql_spells 'Cleric' 'Create Undead' 6 '' '' ''
sql_spells 'Cleric' 'Find the Path' 6 '' '' ''
sql_spells 'Cleric' 'Forbiddance' 6 '' '' ''
sql_spells 'Cleric' 'Harm' 6 '' '' ''
sql_spells 'Cleric' 'Heal' 6 '' '' ''
sql_spells 'Cleric' 'Heros Feast' 6 '' '' ''
sql_spells 'Cleric' 'Planar Ally' 6 '' '' ''
sql_spells 'Cleric' 'True Seeing' 6 '' '' ''
sql_spells 'Cleric' 'Word of Recall' 6 '' '' ''
sql_spells 'Cleric' 'Conjure Celestial' 7 '' '' ''
sql_spells 'Cleric' 'Divine Word' 7 '' '' ''
sql_spells 'Cleric' 'Etherless' 7 '' '' ''
sql_spells 'Cleric' 'Fire Storm' 7 '' '' ''
sql_spells 'Cleric' 'Plane Shift' 7 '' '' ''
sql_spells 'Cleric' 'Regenerate' 7 '' '' ''
sql_spells 'Cleric' 'Resurrection' 7 '' '' ''
sql_spells 'Cleric' 'Symbol' 7 '' '' ''
sql_spells 'Cleric' 'Antimagic Field' 8 '' '' ''
sql_spells 'Cleric' 'Control Weather' 8 '' '' ''
sql_spells 'Cleric' 'Earthquake' 8 '' '' ''
sql_spells 'Cleric' 'Holy Aura' 8 '' '' ''
sql_spells 'Cleric' 'Astral Projection' 9 '' '' ''
sql_spells 'Cleric' 'Gate' 9 '' '' ''
sql_spells 'Cleric' 'Mass Heal' 9 '' '' ''
sql_spells 'Cleric' 'True Resurrection' 9 '' '' ''
sql_spells 'Druid' 'Druidcraft' 0 '' '' ''
sql_spells 'Druid' 'Guidance' 0 '' '' ''
sql_spells 'Druid' 'Mending' 0 '' '' ''
sql_spells 'Druid' 'Posion Spray' 0 '' '' ''
sql_spells 'Druid' 'Produce Flame' 0 '' '' ''
sql_spells 'Druid' 'Resistance' 0 '' '' ''
sql_spells 'Druid' 'Shillelagh' 0 '' '' ''
sql_spells 'Druid' 'Thorn Whip' 0 '' '' ''
sql_spells 'Druid' 'Animal Friendship' 1 '' '' ''
sql_spells 'Druid' 'Charm Person' 1 '' '' ''
sql_spells 'Druid' 'Create or Destroy Water' 1 '' '' ''
sql_spells 'Druid' 'Cure Wounds' 1 '' '' ''
sql_spells 'Druid' 'Detect Magic' 1 '' '' ''
sql_spells 'Druid' 'Detect Poisin and Disease' 1 '' '' ''
sql_spells 'Druid' 'Entangle' 1 '' '' ''
sql_spells 'Druid' 'Faerie Fire' 1 '' '' ''
sql_spells 'Druid' 'Fog Cloud' 1 '' '' ''
sql_spells 'Druid' 'Goodberry' 1 '' '' ''
sql_spells 'Druid' 'Healing Word' 1 '' '' ''
sql_spells 'Druid' 'Jump' 1 '' '' ''
sql_spells 'Druid' 'Longstrider' 1 '' '' ''
sql_spells 'Druid' 'Purify Food and Drink' 1 '' '' ''
sql_spells 'Druid' 'Speak with Animals' 1 '' '' ''
sql_spells 'Druid' 'Thunderwave' 1 '' '' ''
sql_spells 'Druid' 'Animal Messanger' 2 '' '' ''
sql_spells 'Druid' 'Barkskin' 2 '' '' ''
sql_spells 'Druid' 'Beast Sense' 2 '' '' ''
sql_spells 'Druid' 'Darkvision' 2 '' '' ''
sql_spells 'Druid' 'Enhance Ability' 2 '' '' ''
sql_spells 'Druid' 'Find Traps' 2 '' '' ''
sql_spells 'Druid' 'Flame Blade' 2 '' '' ''
sql_spells 'Druid' 'Flaming Sphere' 2 '' '' ''
sql_spells 'Druid' 'Gust of Wind' 2 '' '' ''
sql_spells 'Druid' 'Heat Metal' 2 '' '' ''
sql_spells 'Druid' 'Hold Person' 2 '' '' ''
sql_spells 'Druid' 'Lesser Restpratopm' 2 '' '' ''
sql_spells 'Druid' 'Locate Animals or Plants' 2 '' '' ''
sql_spells 'Druid' 'Locate Object' 2 '' '' ''
sql_spells 'Druid' 'Moonbeam' 2 '' '' ''
sql_spells 'Druid' 'Pass without Trance' 2 '' '' ''
sql_spells 'Druid' 'Protection from Posin' 2 '' '' ''
sql_spells 'Druid' 'Spike Growth' 2 '' '' ''
sql_spells 'Druid' 'Call Lightning' 3 '' '' ''
sql_spells 'Druid' 'Conjure Animals' 3 '' '' ''
sql_spells 'Druid' 'Daylight' 3 '' '' ''
sql_spells 'Druid' 'Dispel Magic' 3 '' '' ''
sql_spells 'Druid' 'Feign Death' 3 '' '' ''
sql_spells 'Druid' 'Meld into Stone' 3 '' '' ''
sql_spells 'Druid' 'Plant Growth' 3 '' '' ''
sql_spells 'Druid' 'Protection from Energy' 3 '' '' ''
sql_spells 'Druid' 'Sleet Storm' 3 '' '' ''
sql_spells 'Druid' 'Speak with Plants' 3 '' '' ''
sql_spells 'Druid' 'Water Breathing' 3 '' '' ''
sql_spells 'Druid' 'Water Walk' 3 '' '' ''
sql_spells 'Druid' 'Wind Wail' 3 '' '' ''
sql_spells 'Druid' 'Blight' 4 '' '' ''
sql_spells 'Druid' 'Confusion' 4 '' '' ''
sql_spells 'Druid' 'Conjure Minor Elements' 4 '' '' ''
sql_spells 'Druid' 'Conjure Woodland Beings' 4 '' '' ''
sql_spells 'Druid' 'Control Water' 4 '' '' ''
sql_spells 'Druid' 'Domminate Beast' 4 '' '' ''
sql_spells 'Druid' 'Freedom of Movement' 4 '' '' ''
sql_spells 'Druid' 'Giant Insect' 4 '' '' ''
sql_spells 'Druid' 'Grasping Vine' 4 '' '' ''
sql_spells 'Druid' 'Hallucinatiory Terrain' 4 '' '' ''
sql_spells 'Druid' 'Ice Storm' 4 '' '' ''
sql_spells 'Druid' 'Locate Creature' 4 '' '' ''
sql_spells 'Druid' 'Polymorph' 4 '' '' ''
sql_spells 'Druid' 'Stone Shape' 4 '' '' ''
sql_spells 'Druid' 'Stoneskin' 4 '' '' ''
sql_spells 'Druid' 'Wall of Fire' 4 '' '' ''
sql_spells 'Druid' 'Amtilife Shell' 5 '' '' ''
sql_spells 'Druid' 'Awaken' 5 '' '' ''
sql_spells 'Druid' 'Commune with Nature' 5 '' '' ''
sql_spells 'Druid' 'Conjure Elemental' 5 '' '' ''
sql_spells 'Druid' 'Contagion' 5 '' '' ''
sql_spells 'Druid' 'Geas' 5 '' '' ''
sql_spells 'Druid' 'Greater Restoration' 5 '' '' ''
sql_spells 'Druid' 'Insect Plauge' 5 '' '' ''
sql_spells 'Druid' 'Mass Cure Wounds' 5 '' '' ''
sql_spells 'Druid' 'Planar Binding' 5 '' '' ''
sql_spells 'Druid' 'Reincarnate' 5 '' '' ''
sql_spells 'Druid' 'Scything' 5 '' '' ''
sql_spells 'Druid' 'Tree Stride' 5 '' '' ''
sql_spells 'Druid' 'Wall of Stone' 5 '' '' ''
sql_spells 'Druid' 'Conjure Fey' 6 '' '' ''
sql_spells 'Druid' 'Find the Path' 6 '' '' ''
sql_spells 'Druid' 'Heal' 6 '' '' ''
sql_spells 'Druid' 'Heros Feast' 6 '' '' ''
sql_spells 'Druid' 'Move Earth' 6 '' '' ''
sql_spells 'Druid' 'Sunbeam' 6 '' '' ''
sql_spells 'Druid' 'Transport via Plants' 6 '' '' ''
sql_spells 'Druid' 'Wall of Thorns' 6 '' '' ''
sql_spells 'Druid' 'Wind Walk' 6 '' '' ''
sql_spells 'Druid' 'Firestorm' 7 '' '' ''
sql_spells 'Druid' 'Mirage Arcane' 7 '' '' ''
sql_spells 'Druid' 'Plane Shift' 7 '' '' ''
sql_spells 'Druid' 'Regenerate' 7 '' '' ''
sql_spells 'Druid' 'Reverse Gravity' 7 '' '' ''
sql_spells 'Druid' 'Animal Shapes' 8 '' '' ''
sql_spells 'Druid' 'Antipathy/Sympathy' 8 '' '' ''
sql_spells 'Druid' 'Control Weather' 8 '' '' ''
sql_spells 'Druid' 'Earthquate' 8 '' '' ''
sql_spells 'Druid' 'Feeblemind' 8 '' '' ''
sql_spells 'Druid' 'Sunburst' 8 '' '' ''
sql_spells 'Druid' 'Tsunami' 8 '' '' ''
sql_spells 'Druid' 'Foresight' 9 '' '' ''
sql_spells 'Druid' 'Shapechange' 9 '' '' ''
sql_spells 'Druid' 'Stormchange' 9 '' '' ''
sql_spells 'Druid' 'True Resurrection' 9 '' '' ''
sql_spells 'Paladin' 'Bless' 1 '' '' ''
sql_spells 'Paladin' 'Command' 1 '' '' ''
sql_spells 'Paladin' 'Compelled Duel' 1 '' '' ''
sql_spells 'Paladin' 'Cure Wounds' 1 '' '' ''
sql_spells 'Paladin' 'Detect Evil and Good' 1 '' '' ''
sql_spells 'Paladin' 'Detect Magic' 1 '' '' ''
sql_spells 'Paladin' 'Detect Posion and Disease' 1 '' '' ''
sql_spells 'Paladin' 'Divine Favor' 1 '' '' ''
sql_spells 'Paladin' 'Heroism' 1 '' '' ''
sql_spells 'Paladin' 'Protection from Evil and Good' 1 '' '' ''
sql_spells 'Paladin' 'Purify Food and Drink' 1 '' '' ''
sql_spells 'Paladin' 'Searing Smite' 1 '' '' ''
sql_spells 'Paladin' 'Shield of Faith' 1 '' '' ''
sql_spells 'Paladin' 'Thunderous Smite' 1 '' '' ''
sql_spells 'Paladin' 'Wrathful Smite' 1 '' '' ''
sql_spells 'Paladin' 'Aid' 2 '' '' ''
sql_spells 'Paladin' 'Branding Smite' 2 '' '' ''
sql_spells 'Paladin' 'Find Steed' 2 '' '' ''
sql_spells 'Paladin' 'Create food and Water' 2 '' '' ''
sql_spells 'Paladin' 'Lesser Restoration' 2 '' '' ''
sql_spells 'Paladin' 'Locate Object' 2 '' '' ''
sql_spells 'Paladin' 'Magic Weapon' 2 '' '' ''
sql_spells 'Paladin' 'Zone of Truth' 2 '' '' ''
sql_spells 'Paladin' 'Aura of Vitality' 3 '' '' ''
sql_spells 'Paladin' 'Blinding Smite' 3 '' '' ''
sql_spells 'Paladin' 'Create Food and Water' 3 '' '' ''
sql_spells 'Paladin' 'Crusaders Mantle' 3 '' '' ''
sql_spells 'Paladin' 'Daylight' 3 '' '' ''
sql_spells 'Paladin' 'Dispel Magic' 3 '' '' ''
sql_spells 'Paladin' 'Elemental Weapon' 3 '' '' ''
sql_spells 'Paladin' 'Magic Circle' 3 '' '' ''
sql_spells 'Paladin' 'Remove Curse' 3 '' '' ''
sql_spells 'Paladin' 'Revividy' 3 '' '' ''
sql_spells 'Paladin' 'Aura of Life' 4 '' '' ''
sql_spells 'Paladin' 'Aura of Purity' 4 '' '' ''
sql_spells 'Paladin' 'Banishment' 4 '' '' ''
sql_spells 'Paladin' 'Death Ward' 4 '' '' ''
sql_spells 'Paladin' 'Locate Creatire' 4 '' '' ''
sql_spells 'Paladin' 'Staggering Smite' 4 '' '' ''
sql_spells 'Paladin' 'Banishing Smite' 5 '' '' ''
sql_spells 'Paladin' 'Circle of Power' 5 '' '' ''
sql_spells 'Paladin' 'Destructive Wave' 5 '' '' ''
sql_spells 'Paladin' 'Dispel Evil and Good' 5 '' '' ''
sql_spells 'Paladin' 'Geas' 5 '' '' ''
sql_spells 'Paladin' 'Raise Dead' 5 '' '' ''
sql_spells 'Ranger' 'Alarm' 1 '' '' ''
sql_spells 'Ranger' 'Animal Friendship' 1 '' '' ''
sql_spells 'Ranger' 'Cure Wounds' 1 '' '' ''
sql_spells 'Ranger' 'Detect Magic' 1 '' '' ''
sql_spells 'Ranger' 'Detect Posion and Disease' 1 '' '' ''
sql_spells 'Ranger' 'Ensnaring Strike' 1 '' '' ''
sql_spells 'Ranger' 'Fog Cloud' 1 '' '' ''
sql_spells 'Ranger' 'Goodberry' 1 '' '' ''
sql_spells 'Ranger' 'Hail of Thorns' 1 '' '' ''
sql_spells 'Ranger' 'Hunters Mark' 1 '' '' ''
sql_spells 'Ranger' 'Jump' 1 '' '' ''
sql_spells 'Ranger' 'Longstrider' 1 '' '' ''
sql_spells 'Ranger' 'Speak with Animals' 1 '' '' ''
sql_spells 'Ranger' 'Animal Messanger' 2 '' '' ''
sql_spells 'Ranger' 'Barkskin' 2 '' '' ''
sql_spells 'Ranger' 'Beast Sense' 2 '' '' ''
sql_spells 'Ranger' 'Cordon of Arrows' 2 '' '' ''
sql_spells 'Ranger' 'Darkvision' 2 '' '' ''
sql_spells 'Ranger' 'Find Traps' 2 '' '' ''
sql_spells 'Ranger' 'Lesser Restoration' 2 '' '' ''
sql_spells 'Ranger' 'Locate Animals or Plants' 2 '' '' ''
sql_spells 'Ranger' 'Locate Object' 2 '' '' ''
sql_spells 'Ranger' 'Pass without Trace' 2 '' '' ''
sql_spells 'Ranger' 'Protection from Poison' 2 '' '' ''
sql_spells 'Ranger' 'Silence' 2 '' '' ''
sql_spells 'Ranger' 'Spike Growth' 2 '' '' ''
sql_spells 'Ranger' 'Conjure Animals' 3 '' '' ''
sql_spells 'Ranger' 'Conjure Barrage' 3 '' '' ''
sql_spells 'Ranger' 'Daylight' 3 '' '' ''
sql_spells 'Ranger' 'Lightning Arrow' 3 '' '' ''
sql_spells 'Ranger' 'Nondetection' 3 '' '' ''
sql_spells 'Ranger' 'Plant Growth' 3 '' '' ''
sql_spells 'Ranger' 'Protection from Energy' 3 '' '' ''
sql_spells 'Ranger' 'Speak with Plants' 3 '' '' ''
sql_spells 'Ranger' 'Water Breathing' 3 '' '' ''
sql_spells 'Ranger' 'Water Walk' 3 '' '' ''
sql_spells 'Ranger' 'Wind Wall' 3 '' '' ''
sql_spells 'Ranger' 'Conjure Woodland Beings' 4 '' '' ''
sql_spells 'Ranger' 'Freedom of Movement' 4 '' '' ''
sql_spells 'Ranger' 'Grasping Vine' 4 '' '' ''
sql_spells 'Ranger' 'Locate Creature' 4 '' '' ''
sql_spells 'Ranger' 'Stoneskin' 4 '' '' ''
sql_spells 'Ranger' 'Commune with Nature' 5 '' '' ''
sql_spells 'Ranger' 'Conjure Volley' 5 '' '' ''
sql_spells 'Ranger' 'Swift Quiver' 5 '' '' ''
sql_spells 'Ranger' 'Tree Stride' 5 '' '' ''
sql_spells 'Sorcerer' 'Acid Splash' 0 '' '' ''
sql_spells 'Sorcerer' 'Blade Ward' 0 '' '' ''
sql_spells 'Sorcerer' 'Chill Touch' 0 '' '' ''
sql_spells 'Sorcerer' 'Dancing Lights' 0 '' '' ''
sql_spells 'Sorcerer' 'Fire Bolt' 0 '' '' ''
sql_spells 'Sorcerer' 'Friends' 0 '' '' ''
sql_spells 'Sorcerer' 'Light' 0 '' '' ''
sql_spells 'Sorcerer' 'Mage Hand' 0 '' '' ''
sql_spells 'Sorcerer' 'Mending' 0 '' '' ''
sql_spells 'Sorcerer' 'Message' 0 '' '' ''
sql_spells 'Sorcerer' 'Minor Illusion' 0 '' '' ''
sql_spells 'Sorcerer' 'Poson Spray' 0 '' '' ''
sql_spells 'Sorcerer' 'Prestidigitation' 0 '' '' ''
sql_spells 'Sorcerer' 'Ray of Frost' 0 '' '' ''
sql_spells 'Sorcerer' 'Shocking Grasp' 0 '' '' ''
sql_spells 'Sorcerer' 'True Strike' 0 '' '' ''
sql_spells 'Sorcerer' 'Burning Hands' 1 '' '' ''
sql_spells 'Sorcerer' 'Charm Person' 1 '' '' ''
sql_spells 'Sorcerer' 'Chromatic Orb' 1 '' '' ''
sql_spells 'Sorcerer' 'Color Spray' 1 '' '' ''
sql_spells 'Sorcerer' 'Comprehend Languages' 1 '' '' ''
sql_spells 'Sorcerer' 'Detect Magic' 1 '' '' ''
sql_spells 'Sorcerer' 'Disguise Self' 1 '' '' ''
sql_spells 'Sorcerer' 'Expeditious Retreat' 1 '' '' ''
sql_spells 'Sorcerer' 'False Life' 1 '' '' ''
sql_spells 'Sorcerer' 'Feather Fall' 1 '' '' ''
sql_spells 'Sorcerer' 'Fog Cloud' 1 '' '' ''
sql_spells 'Sorcerer' 'Jump' 1 '' '' ''
sql_spells 'Sorcerer' 'Mage Armor' 1 '' '' ''
sql_spells 'Sorcerer' 'Magic Missle' 1 '' '' ''
sql_spells 'Sorcerer' 'Ray of Sickness' 1 '' '' ''
sql_spells 'Sorcerer' 'Shield' 1 '' '' ''
sql_spells 'Sorcerer' 'Silent Image' 1 '' '' ''
sql_spells 'Sorcerer' 'Sleep' 1 '' '' ''
sql_spells 'Sorcerer' 'Thunderwave' 1 '' '' ''
sql_spells 'Sorcerer' 'Witch Bolt' 1 '' '' ''
sql_spells 'Sorcerer' 'Alter Self' 2 '' '' ''
sql_spells 'Sorcerer' 'Blindness/Deafness' 2 '' '' ''
sql_spells 'Sorcerer' 'Blur' 2 '' '' ''
sql_spells 'Sorcerer' 'Cloud of Daggers' 2 '' '' ''
sql_spells 'Sorcerer' 'Crown of Darkness' 2 '' '' ''
sql_spells 'Sorcerer' 'Darkness' 2 '' '' ''
sql_spells 'Sorcerer' 'Darkvision' 2 '' '' ''
sql_spells 'Sorcerer' 'Detect Thoughts' 2 '' '' ''
sql_spells 'Sorcerer' 'Enhance Ability' 2 '' '' ''
sql_spells 'Sorcerer' 'Enlarge/Reduce' 2 '' '' ''
sql_spells 'Sorcerer' 'Gust of Wind' 2 '' '' ''
sql_spells 'Sorcerer' 'Hold Person' 2 '' '' ''
sql_spells 'Sorcerer' 'Invisibility' 2 '' '' ''
sql_spells 'Sorcerer' 'Knock' 2 '' '' ''
sql_spells 'Sorcerer' 'Levitate' 2 '' '' ''
sql_spells 'Sorcerer' 'Mirror Image' 2 '' '' ''
sql_spells 'Sorcerer' 'Misty Step' 2 '' '' ''
sql_spells 'Sorcerer' 'Phantasmal Force' 2 '' '' ''
sql_spells 'Sorcerer' 'Scorching Ray' 2 '' '' ''
sql_spells 'Sorcerer' 'See Invisability' 2 '' '' ''
sql_spells 'Sorcerer' 'Shatter' 2 '' '' ''
sql_spells 'Sorcerer' 'Spider Climb' 2 '' '' ''
sql_spells 'Sorcerer' 'Suggestion' 2 '' '' ''
sql_spells 'Sorcerer' 'Web' 2 '' '' ''
sql_spells 'Sorcerer' 'Blink' 3 '' '' ''
sql_spells 'Sorcerer' 'Clairvoyance' 3 '' '' ''
sql_spells 'Sorcerer' 'Counterspell' 3 '' '' ''
sql_spells 'Sorcerer' 'Daylight' 3 '' '' ''
sql_spells 'Sorcerer' 'Dispel Magic' 3 '' '' ''
sql_spells 'Sorcerer' 'Fear' 3 '' '' ''
sql_spells 'Sorcerer' 'Fireball' 3 '' '' ''
sql_spells 'Sorcerer' 'Fly' 3 '' '' ''
sql_spells 'Sorcerer' 'Gaseous Form' 3 '' '' ''
sql_spells 'Sorcerer' 'Haste' 3 '' '' ''
sql_spells 'Sorcerer' 'Hypnotic Pattern' 3 '' '' ''
sql_spells 'Sorcerer' 'Lightning Bolt' 3 '' '' ''
sql_spells 'Sorcerer' 'Major Image' 3 '' '' ''
sql_spells 'Sorcerer' 'Protection from Energy' 3 '' '' ''
sql_spells 'Sorcerer' 'Sleet Storm' 3 '' '' ''
sql_spells 'Sorcerer' 'Slow' 3 '' '' ''
sql_spells 'Sorcerer' 'Stinking Cloud' 3 '' '' ''
sql_spells 'Sorcerer' 'Tongues' 3 '' '' ''
sql_spells 'Sorcerer' 'Water Breathing' 3 '' '' ''
sql_spells 'Sorcerer' 'Water Walk' 3 '' '' ''
sql_spells 'Sorcerer' 'Banishment' 4 '' '' ''
sql_spells 'Sorcerer' 'Blight' 4 '' '' ''
sql_spells 'Sorcerer' 'Confusion' 4 '' '' ''
sql_spells 'Sorcerer' 'Dimension Door' 4 '' '' ''
sql_spells 'Sorcerer' 'Dorminate Beast' 4 '' '' ''
sql_spells 'Sorcerer' 'Greater Invisibility' 4 '' '' ''
sql_spells 'Sorcerer' 'Ice Storm' 4 '' '' ''
sql_spells 'Sorcerer' 'Polymorph' 4 '' '' ''
sql_spells 'Sorcerer' 'Stoneskin' 4 '' '' ''
sql_spells 'Sorcerer' 'Wall of Fire' 4 '' '' ''
sql_spells 'Sorcerer' 'Animate Objects' 5 '' '' ''
sql_spells 'Sorcerer' 'Cloudkill' 5 '' '' ''
sql_spells 'Sorcerer' 'Cone of Cold' 5 '' '' ''
sql_spells 'Sorcerer' 'Creation' 5 '' '' ''
sql_spells 'Sorcerer' 'Dominate Person' 5 '' '' ''
sql_spells 'Sorcerer' 'Hold Monster' 5 '' '' ''
sql_spells 'Sorcerer' 'Insect Plauge' 5 '' '' ''
sql_spells 'Sorcerer' 'Seeming' 5 '' '' ''
sql_spells 'Sorcerer' 'Telekinesis' 5 '' '' ''
sql_spells 'Sorcerer' 'Teleportation Circle' 5 '' '' ''
sql_spells 'Sorcerer' 'Wall of Stone' 5 '' '' ''
sql_spells 'Sorcerer' 'Arcane Gate' 6 '' '' ''
sql_spells 'Sorcerer' 'Chain of Lightning' 6 '' '' ''
sql_spells 'Sorcerer' 'Circle of Death' 6 '' '' ''
sql_spells 'Sorcerer' 'Disintegrate' 6 '' '' ''
sql_spells 'Sorcerer' 'Eyebite' 6 '' '' ''
sql_spells 'Sorcerer' 'Globe of Invulnerability' 6 '' '' ''
sql_spells 'Sorcerer' 'Mass Suggestion' 6 '' '' ''
sql_spells 'Sorcerer' 'Move Earth' 6 '' '' ''
sql_spells 'Sorcerer' 'Sunbeam' 6 '' '' ''
sql_spells 'Sorcerer' 'True Seeing' 6 '' '' ''
sql_spells 'Sorcerer' 'Delayed Blast Fireball' 7 '' '' ''
sql_spells 'Sorcerer' 'Etherealness' 7 '' '' ''
sql_spells 'Sorcerer' 'Finger of Death' 7 '' '' ''
sql_spells 'Sorcerer' 'Fire Storm' 7 '' '' ''
sql_spells 'Sorcerer' 'Plane Shift' 7 '' '' ''
sql_spells 'Sorcerer' 'Prismatic Spray' 7 '' '' ''
sql_spells 'Sorcerer' 'Reverse Gravity' 7 '' '' ''
sql_spells 'Sorcerer' 'Teleport' 7 '' '' ''
sql_spells 'Sorcerer' 'Dominate Monster' 8 '' '' ''
sql_spells 'Sorcerer' 'Earthquake' 8 '' '' ''
sql_spells 'Sorcerer' 'Incendiary Cloud' 8 '' '' ''
sql_spells 'Sorcerer' 'Power Word Stun' 8 '' '' ''
sql_spells 'Sorcerer' 'Sunburst' 8 '' '' ''
sql_spells 'Sorcerer' 'Gate' 9 '' '' ''
sql_spells 'Sorcerer' 'Meteor Swarm' 9 '' '' ''
sql_spells 'Sorcerer' 'Power Word Kill' 9 '' '' ''
sql_spells 'Sorcerer' 'Time Stop' 9 '' '' ''
sql_spells 'Sorcerer' 'Wish' 9 '' '' ''
sql_spells 'Warlock' 'Blade Ward' 0 '' '' ''
sql_spells 'Warlock' 'Chill Touch' 0 '' '' ''
sql_spells 'Warlock' 'Eldritch Blast' 0 '' '' ''
sql_spells 'Warlock' 'Friends' 0 '' '' ''
sql_spells 'Warlock' 'Mage Hand' 0 '' '' ''
sql_spells 'Warlock' 'Minor Illusion' 0 '' '' ''
sql_spells 'Warlock' 'Poison Spray' 0 '' '' ''
sql_spells 'Warlock' 'Prestidigitation' 0 '' '' ''
sql_spells 'Warlock' 'True Strike' 0 '' '' ''
sql_spells 'Warlock' 'Armor of Agathys' 1 '' '' ''
sql_spells 'Warlock' 'Arms of Hadar' 1 '' '' ''
sql_spells 'Warlock' 'Charm Person' 1 '' '' ''
sql_spells 'Warlock' 'Comprehend Languages' 1 '' '' ''
sql_spells 'Warlock' 'Expeditious Retreat' 1 '' '' ''
sql_spells 'Warlock' 'Hellish Rebuke' 1 '' '' ''
sql_spells 'Warlock' 'Hex' 1 '' '' ''
sql_spells 'Warlock' 'Illusory Script' 1 '' '' ''
sql_spells 'Warlock' 'Protection from Evil and Good' 1 '' '' ''
sql_spells 'Warlock' 'Unseen Servent' 1 '' '' ''
sql_spells 'Warlock' 'Witch Bolt' 1 '' '' ''
sql_spells 'Warlock' 'Cloud of Daggers' 2 '' '' ''
sql_spells 'Warlock' 'Crown of Madness' 2 '' '' ''
sql_spells 'Warlock' 'Darkness' 2 '' '' ''
sql_spells 'Warlock' 'Enthrall' 2 '' '' ''
sql_spells 'Warlock' 'Hold Person' 2 '' '' ''
sql_spells 'Warlock' 'Invisiability' 2 '' '' ''
sql_spells 'Warlock' 'Mirror Image' 2 '' '' ''
sql_spells 'Warlock' 'Misty Step' 2 '' '' ''
sql_spells 'Warlock' 'Ray of Enfeeblement' 2 '' '' ''
sql_spells 'Warlock' 'Shatter' 2 '' '' ''
sql_spells 'Warlock' 'Spider Climb' 2 '' '' ''
sql_spells 'Warlock' 'Suggestion' 2 '' '' ''
sql_spells 'Warlock' 'Counterspell' 3 '' '' ''
sql_spells 'Warlock' 'Dispell Magic' 3 '' '' ''
sql_spells 'Warlock' 'Fear' 3 '' '' ''
sql_spells 'Warlock' 'Fly' 3 '' '' ''
sql_spells 'Warlock' 'Gaseous Form' 3 '' '' ''
sql_spells 'Warlock' 'Hunger of Hadar' 3 '' '' ''
sql_spells 'Warlock' 'Hypnotic Pattern' 3 '' '' ''
sql_spells 'Warlock' 'Magic Circle' 3 '' '' ''
sql_spells 'Warlock' 'Major Image' 3 '' '' ''
sql_spells 'Warlock' 'Remove Curse' 3 '' '' ''
sql_spells 'Warlock' 'Tounges' 3 '' '' ''
sql_spells 'Warlock' 'Vampiric Touch' 3 '' '' ''
sql_spells 'Warlock' 'Banishment' 4 '' '' ''
sql_spells 'Warlock' 'Blight' 4 '' '' ''
sql_spells 'Warlock' 'Dimension Door' 4 '' '' ''
sql_spells 'Warlock' 'Hallucinatonry Terrain' 4 '' '' ''
sql_spells 'Warlock' 'Contact Other Plane' 5 '' '' ''
sql_spells 'Warlock' 'Dream' 5 '' '' ''
sql_spells 'Warlock' 'Hold Monster' 5 '' '' ''
sql_spells 'Warlock' 'Scrying' 5 '' '' ''
sql_spells 'Warlock' 'Arcane Gate' 6 '' '' ''
sql_spells 'Warlock' 'Circle of Death' 6 '' '' ''
sql_spells 'Warlock' 'Conjure Fey' 6 '' '' ''
sql_spells 'Warlock' 'Create Undead' 6 '' '' ''
sql_spells 'Warlock' 'Eyebite' 6 '' '' ''
sql_spells 'Warlock' 'Flesh to Stone' 6 '' '' ''
sql_spells 'Warlock' 'Mass Suggestion' 6 '' '' ''
sql_spells 'Warlock' 'True Seeing' 6 '' '' ''
sql_spells 'Warlock' 'Etherealness' 7 '' '' ''
sql_spells 'Warlock' 'Finger of Death' 7 '' '' ''
sql_spells 'Warlock' 'Forecage' 7 '' '' ''
sql_spells 'Warlock' 'Plane Shift' 7 '' '' ''
sql_spells 'Warlock' 'Demiplane' 8 '' '' ''
sql_spells 'Warlock' 'Dominate Monster' 8 '' '' ''
sql_spells 'Warlock' 'Feeblemind' 8 '' '' ''
sql_spells 'Warlock' 'Glibness' 8 '' '' ''
sql_spells 'Warlock' 'Power Word Stun' 8 '' '' ''
sql_spells 'Warlock' 'Astral Projection' 9 '' '' ''
sql_spells 'Warlock' 'Foresight' 9 '' '' ''
sql_spells 'Warlock' 'Imprisonment' 9 '' '' ''
sql_spells 'Warlock' 'Power Word Kill' 9 '' '' ''
sql_spells 'Warlock' 'True Polymorph' 9 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 0 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 1 '' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 2'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 3'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 4'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 5'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 6'' '' ''
sql_spells 'Wizard' '' 7'' '' ''
sql_spells 'Wizard' '' 7'' '' ''
sql_spells 'Wizard' '' 7'' '' ''
sql_spells 'Wizard' '' 7'' '' ''
sql_spells 'Wizard' '' 7'' '' ''
sql_spells 'Wizard' '' 7'' '' ''
sql_spells 'Wizard' '' 7'' '' ''
sql_spells 'Wizard' '' 7'' '' ''
sql_spells 'Wizard' '' 7'' '' ''
sql_spells 'Wizard' '' 7'' '' ''
sql_spells 'Wizard' '' 7'' '' ''
sql_spells 'Wizard' '' 7'' '' ''
sql_spells 'Wizard' '' 7'' '' ''
sql_spells 'Wizard' '' 7'' '' ''
sql_spells 'Wizard' '' 7'' '' ''
sql_spells 'Wizard' '' 8'' '' ''
sql_spells 'Wizard' '' 8'' '' ''
sql_spells 'Wizard' '' 8'' '' ''
sql_spells 'Wizard' '' 8'' '' ''
sql_spells 'Wizard' '' 8'' '' ''
sql_spells 'Wizard' '' 8'' '' ''
sql_spells 'Wizard' '' 8'' '' ''
sql_spells 'Wizard' '' 8'' '' ''
sql_spells 'Wizard' '' 8'' '' ''
sql_spells 'Wizard' '' 8'' '' ''
sql_spells 'Wizard' '' 8'' '' ''
sql_spells 'Wizard' '' 8'' '' ''
sql_spells 'Wizard' '' 8'' '' ''
sql_spells 'Wizard' '' 9'' '' ''
sql_spells 'Wizard' '' 9'' '' ''
sql_spells 'Wizard' '' 9'' '' ''
sql_spells 'Wizard' '' 9'' '' ''
sql_spells 'Wizard' '' 9'' '' ''
sql_spells 'Wizard' '' 9'' '' ''
sql_spells 'Wizard' '' 9'' '' ''
sql_spells 'Wizard' '' 9'' '' ''
sql_spells 'Wizard' '' 9'' '' ''
sql_spells 'Wizard' '' 9'' '' ''
sql_spells 'Wizard' '' 9'' '' ''
sql_spells 'Wizard' '' 9'' '' ''
